# Generated by Django 4.1.1 on 2022-11-22 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='questions',
            field=models.ManyToManyField(null=True, related_name='categories', to='quizzes.questionmodel'),
        ),
    ]
