# Generated by Django 4.1.1 on 2022-11-22 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_alter_categorymodel_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionmodel',
            name='quizzes',
        ),
        migrations.AddField(
            model_name='quizmodel',
            name='questions',
            field=models.ManyToManyField(related_name='quizzes', to='quizzes.questionmodel'),
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='questions',
            field=models.ManyToManyField(related_name='categories', to='quizzes.questionmodel'),
        ),
        migrations.AlterField(
            model_name='questionmodel',
            name='question_text',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
