# Generated by Django 4.1.1 on 2022-11-23 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_remove_questionmodel_quizzes_quizmodel_questions_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorymodel',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='questionmodel',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='quizmodel',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='quizresultmodel',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='quizmodel',
            name='creator',
        ),
        migrations.AlterField(
            model_name='quizmodel',
            name='time_constraint_in_seconds',
            field=models.IntegerField(default=60),
        ),
    ]
