# Generated by Django 4.1.1 on 2022-11-23 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_alter_categorymodel_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizresultmodel',
            name='employee',
        ),
    ]
