# Generated by Django 4.1.1 on 2022-11-25 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizzes', '0006_quizresultmodel_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizmodel',
            name='creator',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, related_name='created_quizzes', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
