# Generated by Django 4.1.1 on 2022-11-21 21:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='The first name can contain only latin letters.', regex='^[A-Za-z]*$')])),
                ('last_name', models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator(message='The last name can contain only latin letters.', regex='^[A-Za-z]*$')])),
                ('current_position', models.CharField(max_length=60)),
                ('is_active', models.BooleanField(default=False)),
                ('company_join_date', models.DateField(auto_now_add=True)),
                ('role', models.CharField(choices=[('ad', 'admin'), ('em', 'employee')], default='em', max_length=2)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='ReviewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('position_before', models.CharField(blank=True, max_length=60)),
                ('position_after', models.CharField(blank=True, max_length=60)),
                ('salary_change', models.IntegerField(default=0)),
                ('review_date', models.DateField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reviews',
            },
        ),
    ]
