# Generated by Django 4.1.1 on 2022-11-22 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewmodel',
            name='title',
            field=models.CharField(default='Annual salary review', max_length=60),
            preserve_default=False,
        ),
    ]
